/*CREATE TABLE R1*/

CREATE TABLE R1( K NUMBER(2),A NUMBER(2),B NUMBER(2),C NUMBER(2),

ADD CONSTRAINT R1_K_PK PRIMARY KEY(K));

DESC R1K; /* TO SEE THE TABLE CREATED*/

/*INSERT VALUES IN TO THE TABLE R1/

INSERT INTO RI(K,A,B,C) VALUES('4','2','0','6');

INSERT INTO RI(K,A,B,C) VALUES('5','2','0','5');

INSERT INTO RI(K,A,B,C) VALUES('1','1','3','8');

INSERT INTO RI(K,A,B,C) VALUES('2','1','3','7');

INSERT INTO RI(K,A,B,C) VALUES('3','2','3','3');

/* SEE THE VALUES IN TABLE R1*/

SELECT * FROM R1;




/* CREATE TABLE R2*/

CREATE TABLE R2( K NUMBER(2),D NUMBER(2),E NUMBER(2),

ADD CONSTRAINT R2_K_PK PRIMARY KEY(K),

ADD CONSTRAINT R2_K_FK FOREIGN KEY(K) REFERENCES R1(K));

DESC R2; 
/* TO SEE THE TABLE CREATED*/

/* INSERT VALUES IN TO THE TABLE R2*/

INSERT INTO R2(D,E) VALUES('1','6');

INSERT INTO R2(D,E) VALUES('1','5');

INSERT INTO R2(D,E) VALUES('1','8');

INSERT INTO R2(D,E) VALUES('1','7');

INSERT INTO R2(D,E) VALUES('1','3');

/* SEE THE VALUES IN TABLE R2*/

SELECT * FROM R2;




/* CREATE TABLE R3*/

CREATE TABLE R3( A NUMBER(2),A1 NUMBER(2),A2 NUMBER(2),A3 NUMBER(2),

ADD CONSTRAINT R3_A_PK PRIMARY KEY(A),

ADD CONSTRAINT R3_A_FK FOREIGN KEY(A) REFERENCES R1(A)
);

DESC R3; 
/* TO SEE THE TABLE CREATED*/

/* INSERT VALUES IN TO THE TABLE R3*
/
INSERT INTO R3(A1,A2,A3) VALUES('4','6','8')
;
INSERT INTO R3(A1,A2,A3) VALUES('4','6','8');

INSERT INTO R3(A1,A2,A3) VALUES('2','3','4');

INSERT INTO R3(A1,A2,A3) VALUES('2','3','4');

INSERT INTO R3(A1,A2,A3) VALUES('4','6','8');

/* TO SEE THE VALUES IN TABLE R3*/

SELECT * FROM R3;



 

CREATE TABLE R4( B NUMBER(2),B1 NUMBER(2),B2 NUMBER(2),

ADD CONSTRAINT R4_B_PK PRIMARY KEY(B),

ADD CONSTRAINT R4_B_FK FOREIGN KEY(B) REFERENCES R1(B));

DESC R4; /* TO SEE THE TABLE CREATED*/

/* INSERT VALUES IN TO THE TABLE R4*/

INSERT INTO R3(B1,B2) VALUES('0','0');

INSERT INTO R4(B1,B2) VALUES('0','0');

INSERT INTO R4(B1,B2) VALUES('9','27');

INSERT INTO R4(B1,B2) VALUES('9','27');

INSERT INTO R4(B1,B2) VALUES('9','27');

/* TO SEE THE VALUES FROM R4 */

SELECT * FROM R4;




/*CREATE TABLE R5*/

CREATE TABLE R5( C NUMBER(2),C1 NUMBER(2),C2 NUMBER(2),C3 NUMBER(2),C4 NUMBER(2),C5 NUMBER(2),

ADD CONSTRAINT R5_C_PK PRIMARY KEY(C)
);

DESC R5; /* TO SEE THE TABLE CREATED*/

/* INSERT VALUES IN TO THE TABLE R5*/


INSERT INTO R5(C,C1,C2,C3,C4,C5) VALUES('4','2','0','6','1','6');

 INSERT INTO R5(C,C1,C2,C3,C4,C5) VALUES('5','2','0','5','1','5');

INSERT INTO R5(C,C1,C2,C3,C4,C5) VALUES('1','1','3','8','1','8');

INSERT INTO R5(C,C1,C2,C3,C4,C5) VALUES('2','1','3','7','1','7');

INSERT INTO R5(C,C1,C2,C3,C4,C5) VALUES('3','2','3','3','1','3');


/* SEE THE VALUES IN TABLE R5*/

SELECT * FROM R5;




























